// Generated by tsc from JSDoc (npm run manifest). Do not edit.
declare const _default: {
    "1bit": string[];
    gameboy: string[];
    grayscale: string[];
    cga: string[];
    sepia: string[];
    "pico-8": string[];
};
export default _default;
