// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Resolve with `value` after `wait` milliseconds, or on the next microtask
 * if `wait` is omitted.
 * @template T
 * @param {number} [wait]
 * @param {T} [val]
 * @returns {Promise<T>}
 */
declare function _default<T>(wait?: number, val?: T): Promise<T>;
