// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Wait, then resolve with `value`:
 *
 * - `delay()` waits for the next microtask.
 * - `delay(ms)` waits `ms` milliseconds (a promise-based `setTimeout`).
 * - `delay({ fps })` waits one frame period (`1000 / fps` ms), finishing on
 *   an animation frame. Use it to pace a loop. Like all
 *   `requestAnimationFrame` work, it waits while the page is hidden.
 *
 * Rejects with a `RangeError` if `fps` isn't a positive number.
 * @template T
 * @param {number | { fps: number }} [wait]
 * @param {T} [value]
 * @returns {Promise<T>}
 */
declare function _default<T>(wait?: number | {
    fps: number;
}, value?: T): Promise<T>;
