// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Wait, then resolve with `value`:
 *
 * - `delay()` waits for the next microtask.
 * - `delay(ms)` waits `ms` milliseconds (a promise-based `setTimeout`).
 * - `delay({ fps })` waits one frame period (`1000 / fps` ms), finishing on
 *   an animation frame. Use it to pace a loop. Like all
 *   `requestAnimationFrame` work, it waits while the page is hidden.
 *
 * Pass an `AbortSignal` as `signal` (in the options, or in the `{ fps }`
 * object) to cancel the wait: it then rejects with `signal.reason`, like
 * `fetch`. Rejects with a `RangeError` if `fps` isn't a positive number.
 * @template T
 * @param {number | { fps: number, signal?: AbortSignal }} [wait]
 * @param {T} [value]
 * @param {{ signal?: AbortSignal }} [options]
 * @returns {Promise<T>}
 */
declare function _default<T>(wait?: number | {
    fps: number;
    signal?: AbortSignal;
}, value?: T, { signal }?: {
    signal?: AbortSignal;
}): Promise<T>;
