// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * localStorageCycler with a built-in handler that puts the current value
 * on the target element(s) as a class.
 * @param {Element | Element[]} targets
 * @param {string} key localStorage key
 * @param {...string} classes the values to cycle through ("" = no class)
 * @returns {import("../localstorage-cycler/index.mjs").Cycler}
 */
declare function _default(targets: Element | Element[], key: string, ...classes: string[]): import("../localstorage-cycler/index.mjs").Cycler;
