// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Remove these classes from every element that has them once the page is
 * ready: the window has loaded (immediately, if it already has), and every
 * `<define-component>` and `<polyfill-window>` on the page has finished,
 * whether it succeeded or failed.
 * @param {...string} classNames
 * @returns {Promise<void>} resolves once the classes are removed
 */
declare function _default(...classNames: string[]): Promise<void>;
