// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Remove these classes from every element that has them once the window
 * has loaded (immediately, if it already has).
 * @param {...string} classNames
 * @returns {void}
 */
declare function _default(...classNames: string[]): void;
