// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** Re-resolves body's first suitable child on every call, unlike the
 * default export below (a one-shot snapshot from import time). Use this
 * when you need a fresh read rather than the value from whenever this
 * module first loaded.
 * @returns {Element} */
export declare function resolveFirst(): Element;
/** Body's first meaningful child element (created if needed), resolved at import time. @type {Element} */
declare const _default: Element;
export default _default;
