// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * @param {Node|null} node
 * @param {"nextSibling"|"previousSibling"} direction
 * @returns {Node|null} the first node in that direction that isn't
 *   whitespace-only text or a comment (or null if the search runs out).
 */
export declare function skipInsignificant(node: Node | null, direction: "nextSibling" | "previousSibling"): Node | null;
