// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export type ContainerSize = {
    width: number;
    height: number;
    em: number;
    rem: number;
};
/**
 * Compile a media-query-style string into a test over a container's size.
 * An empty query always matches.
 * @param {string} query
 * @returns {(size: ContainerSize) => boolean}
 */
export declare function compileQuery(query: string): (size: ContainerSize) => boolean;
/**
 * A MediaQueryList look-alike whose query is evaluated against `container`'s
 * content box. Fires "change" when `matches` flips.
 */
export declare class ContainerQueryList extends EventTarget {
    #private;
    media: string;
    /**
     * @param {string} media
     * @param {Element | null} container  null means "no container": only an empty query matches
     */
    constructor(media: string, container: Element | null);
    get matches(): boolean;
    get onchange(): null;
    set onchange(handler: null);
    addEventListener(type: any, listener: any, options: any): void;
    removeEventListener(type: any, listener: any, options: any): void;
    /** @param {ContainerSize} size */
    update(size: ContainerSize): void;
}
/**
 * The container an element with a `container` attribute measures: its
 * parent for an empty value, else the closest ancestor matching the value
 * as a selector. Null if the attribute is absent.
 * @param {Element} element
 * @returns {Element | null | undefined}  undefined = viewport mode
 */
export declare function containerFor(element: Element): Element | null | undefined;
