// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * @template T
 * @param {number} [fps=60] frames per second; must be > 0
 * @param {T} [value]
 * @returns {Promise<T>}
 */
declare function _default<T>(fps?: number, value?: T): Promise<T>;
