// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** Normalize a language name ("javascript", "language-ts", …) to js/css/html, or null. */
export declare const languageOf: (name: any) => any;
/**
 * @param {string} text
 * @param {"js" | "css" | "html"} language
 * @param {number} [offset] added to every span (for embedded code)
 * @returns {[string, number, number][]}
 */
export declare function tokenize(text: string, language: "js" | "css" | "html", offset?: number): [string, number, number][];
