// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * @param {Element} element
 * @param {string} attribute
 * @param {string[]} values every value in the cycle
 * @param {string} value the current one
 */
export declare function applyValue(element: Element, attribute: string, values: string[], value: string): void;
/**
 * Remove whatever the cycle put on `element`, and nothing else: its classes,
 * or the attribute if it holds one of the cycle's values.
 * @param {Element} element
 * @param {string} attribute
 * @param {string[]} values
 */
export declare function clearValue(element: Element, attribute: string, values: string[]): void;
