// Generated by tsc from JSDoc (npm run manifest). Do not edit.
declare const HYDRATED: unique symbol;
declare const TEARDOWN: unique symbol;
/**
 * @param {(this: object, opts: { finalizer: (fn: Function) => void, dehydrator: (fn: Function) => void }) => Promise<void>} hydrate
 * @param {string} [name] Method name for the hydrate operation.
 * @param {string} [dehydrateName] Method name for its counterpart. Defaults to `de${name}`.
 * @returns {Record<string, () => Promise<object>>} methods to mix into a prototype
 */
declare const Hydratable: (hydrate: (this: object, opts: {
    finalizer: (fn: Function) => void;
    dehydrator: (fn: Function) => void;
}) => Promise<void>, name?: string, dehydrateName?: string) => Record<string, () => Promise<object>>;
export default Hydratable;
export { HYDRATED, TEARDOWN };
