// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * localStorageCycler with a built-in handler that puts the current value on
 * the target element(s): as one class among their others (the default), or
 * as the value of another attribute.
 * @param {Element | Element[]} targets
 * @param {string} key localStorage key
 * @param {string[]} values the values to cycle through ("" = none)
 * @param {{ attribute?: string }} [options] the attribute to set (default `class`)
 * @returns {import("../localstorage-cycler/index.mjs").Cycler}
 */
declare function _default(targets: Element | Element[], key: string, values: string[], { attribute }?: {
    attribute?: string;
}): import("../localstorage-cycler/index.mjs").Cycler;
