// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * @typedef {Element[] & {
 *   stop(): void,
 *   addEventListener(type: "change", listener: (event: Event) => void, options?: boolean | AddEventListenerOptions): void,
 *   removeEventListener(type: "change", listener: (event: Event) => void, options?: boolean | EventListenerOptions): void,
 * }} LiveElementList
 */
export type LiveElementList = Element[] & {
    stop(): void;
    addEventListener(type: "change", listener: (event: Event) => void, options?: boolean | AddEventListenerOptions): void;
    removeEventListener(type: "change", listener: (event: Event) => void, options?: boolean | EventListenerOptions): void;
};
/**
 * `querySelectorAll` that stays current: the returned array is refreshed in
 * place as elements are added to or removed from `root`, and fires `change`
 * when its contents change. Call `stop()` on it when done.
 * @param {string} selector
 * @param {ParentNode} [root] the root to search and watch (default: document)
 * @returns {LiveElementList}
 */
declare const liveQuerySelector: (selector: string, root?: ParentNode) => LiveElementList;
export default liveQuerySelector;
