// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * `clamp(min, max)(value)`: restrict a number to the range [min, max].
 * @param {number} min
 * @param {number} max
 * @returns {(value: number) => number}
 */
declare function _default(min: number, max: number): (value: number) => number;
