// Generated by tsc from JSDoc (npm run manifest). Do not edit.
declare const MutableNodeList: {
    new (): {
        [index: number]: Node;
        item(i?: number): Node;
        push(...nodes: any[]): number;
        pop(): any;
        shift(): any;
        unshift(...nodes: any[]): number;
        [Symbol.iterator](): ArrayIterator<any>;
        values(): ArrayIterator<any>;
        keys(): ArrayIterator<number>;
        entries(): ArrayIterator<[number, any]>;
        forEach(callback: any, thisArg: any): void;
        readonly length: number;
    };
};
/**
 * Create a NodeList you can push to, pop from, shift, and unshift.
 * @param {...Node} nodes initial contents
 * @returns {InstanceType<typeof MutableNodeList>}
 */
declare const createMutableNodeList: (...nodes: Node[]) => InstanceType<typeof MutableNodeList>;
export { MutableNodeList };
export default createMutableNodeList;
