// Emits .d.mts declarations for the plain-function modules from their
// JSDoc (tsconfig.types.json), next to each source file. Element
// declarations come from scripts/manifest-outputs.mjs instead.
//
// Previous output is deleted first: modules import each other's types, and
// tsc would otherwise read last run's .d.mts as input (stale, and it refuses
// to overwrite inputs). Generated files carry HEADER so they can be found.
import { execFileSync } from "node:child_process";
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const HEADER = "// Generated by tsc from JSDoc (npm run manifest). Do not edit.\n";

const allFiles = async (dir) => {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await allFiles(path)));
    else out.push(path);
  }
  return out;
};
const declarations = async () => (await allFiles(join(ROOT, "src"))).filter((file) => file.endsWith(".d.mts"));

for (const file of await declarations()) {
  if ((await readFile(file, "utf8")).startsWith(HEADER)) await rm(file);
}
execFileSync(process.execPath, [join(ROOT, "node_modules/typescript/bin/tsc"), "-p", join(ROOT, "tsconfig.types.json")], {
  stdio: "inherit",
});
let count = 0;
for (const file of await declarations()) {
  const text = await readFile(file, "utf8");
  if (text.startsWith("// Generated")) continue; // manifest-generated, or already headed
  await writeFile(file, HEADER + text);
  count++;
}
console.log(`✅ ${count} declaration file(s) from JSDoc`);
