// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export default _default;
/**
 * Curried `customElements.define`: `definetag(Class)("tag-name")`.
 * @param {CustomElementConstructor} elementClass
 * @returns {(name: string) => void}
 */
declare function _default(elementClass: CustomElementConstructor): (name: string) => void;
