// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Run `command` on `target`, with `source` as the event's source. Returns
 * false if there's no target, or the command isn't built in or `--custom`.
 * @param {Element | null | undefined} target
 * @param {string | null | undefined} command
 * @param {Element} source
 * @returns {boolean}
 */
export declare function invokeCommand(target: Element | null | undefined, command: string | null | undefined, source: Element): boolean;
/**
 * The element an element's `commandfor` attribute names (by id, in its own
 * document or shadow root), like a button's `commandForElement`.
 * @param {Element} element
 * @returns {Element | null}
 */
export declare function commandForElement(element: Element): Element | null;
