// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * @typedef {{ value: string, key: string, index: number, events: unknown[] }} CycleChange
 *   What a change handler receives.
 * @typedef {{ value: string, key: string, index: number, result: unknown }} CycleResult
 *   What stepping returns (`result` is the handler's return value).
 * @typedef {((...events: unknown[]) => CycleResult) & {
 *   previous(...events: unknown[]): CycleResult,
 *   peek(): { value: string, key: string, index: number },
 *   set(value: string, ...events: unknown[]): CycleResult,
 * }} Cycler
 *   Call it to step forward; it also carries previous/peek/set.
 */
export type CycleChange = {
    value: string;
    key: string;
    index: number;
    events: unknown[];
};
export type CycleResult = {
    value: string;
    key: string;
    index: number;
    result: unknown;
};
export type Cycler = ((...events: unknown[]) => CycleResult) & {
    previous(...events: unknown[]): CycleResult;
    peek(): {
        value: string;
        key: string;
        index: number;
    };
    set(value: string, ...events: unknown[]): CycleResult;
};
export default _default;
/**
 * Cycle a localStorage value through a fixed list. Pass an optional change
 * handler before the values: `localStorageCycler(key, handler, "a", "b")`.
 * @param {string} key
 * @param {...(string | ((change: CycleChange) => unknown))} values
 * @returns {Cycler}
 */
declare function _default(key: string, ...values: (string | ((change: CycleChange) => unknown))[]): Cycler;
