// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Fires "define" (with the effect's `name` in `detail`) when an effect is
 * registered, so a <pixel-canvas> waiting on it can redraw.
 */
export declare const effectRegistry: EventTarget;
export type EffectParams = Record<string, string> & {
    args: string[];
};
export type Effect = {
    name: string;
    params: string[];
    apply: (image: ImageData, params: EffectParams) => ImageData | void;
};
/**
 * @typedef {Record<string, string> & { args: string[] }} EffectParams
 *   Parameter values as written (strings), by name. `args` holds
 *   positional values beyond the declared parameters.
 * @typedef {{ name: string, params: string[], apply: (image: ImageData, params: EffectParams) => ImageData | void }} Effect
 */
/**
 * Register an effect under `name`: usable as `name(…)` in an `effects`
 * attribute and as a `<pixel-name>` element (unless that tag is taken).
 * `params` lists the parameter names, in the order positional values fill
 * them. `apply` gets the ImageData and the parameter values (strings), and
 * returns an ImageData (or changes the one it got).
 * @param {string} name
 * @param {(image: ImageData, params: EffectParams) => ImageData | void} apply
 * @param {{ params?: string[], element?: boolean }} [options]
 * @returns {Effect}
 */
export declare function definePixelEffect(name: string, apply: (image: ImageData, params: EffectParams) => ImageData | void, { params, element }?: {
    params?: string[];
    element?: boolean;
}): Effect;
/**
 * The registered effect called `name`, if any.
 * @param {string} name
 * @returns {Effect | undefined}
 */
export declare const getPixelEffect: (name: string) => Effect | undefined;
/**
 * Parse an `effects` attribute into calls, in order:
 * `"mosaic(4) palette(gameboy, ordered)"` ->
 * `[{ name: "mosaic", args: ["4"] }, { name: "palette", args: ["gameboy", "ordered"] }]`.
 * Parentheses are optional for an effect with no arguments (`outline`).
 * @param {string} text
 * @returns {{ name: string, args: string[] }[]}
 */
export declare function parseEffects(text: string): {
    name: string;
    args: string[];
}[];
/**
 * Turn a call's arguments into named parameters. An argument whose first
 * word is a parameter name is named (`contrast 1.3`); the rest fill the
 * unnamed parameters in order (`palette(gameboy, ordered)`).
 * @param {Effect} effect
 * @param {string[]} args
 * @returns {EffectParams}
 */
export declare function resolveParams(effect: Effect, args: string[]): EffectParams;
/**
 * Base class for effect elements. With a static `effect` (as
 * definePixelEffect makes), it applies that effect with its attributes as
 * the parameters; otherwise override `apply()`.
 */
export declare class PixelEffect extends HTMLElement {
    /** @type {Effect | undefined} */
    static effect: Effect | undefined;
    /**
     * The effect's parameters, read from this element's attributes.
     * @type {EffectParams}
     * @readonly
     */
    readonly get params(): EffectParams;
    /**
     * Transform the image (by default, with this element's effect).
     * @param {ImageData} image
     * @returns {ImageData}
     */
    apply(image: ImageData): ImageData;
    /**
     * Whether the effect is switched off (the image passes through).
     * Mirrors the `disabled` attribute.
     * @type {boolean}
     */
    get disabled(): boolean;
    set disabled(value: boolean);
    /**
     * Ask the enclosing <pixel-canvas> to redraw, after a change it can't
     * see (attribute changes are seen already).
     */
    invalidate(): void;
}
/**
 * A parameter as a number, clamped, or `fallback` if it isn't one.
 * @param {string | undefined | null} value
 * @param {number} fallback
 * @param {{ min?: number, max?: number }} [range]
 * @returns {number}
 */
export declare function number(value: string | undefined | null, fallback: number, { min, max }?: {
    min?: number;
    max?: number;
}): number;
/**
 * @param {string | undefined | null} color
 * @returns {[number, number, number, number] | null} null if it isn't a color
 */
export declare function parseColor(color: string | undefined | null): [number, number, number, number] | null;
/**
 * Perceived brightness of an RGB color, 0–255.
 * @param {number} r @param {number} g @param {number} b
 * @returns {number}
 */
export declare const luminance: (r: number, g: number, b: number) => number;
