// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Base class for pixel effects: override `apply(image)`.
 */
export declare class PixelFilter extends HTMLElement {
    /**
     * Transform the image. The default passes it through.
     * @param {ImageData} image
     * @returns {ImageData}
     */
    apply(image: ImageData): ImageData;
    /**
     * Whether the effect is switched off (the image passes through).
     * Mirrors the `disabled` attribute.
     * @type {boolean}
     */
    get disabled(): boolean;
    set disabled(value: boolean);
    /**
     * Ask the enclosing <pixel-canvas> to redraw, after a change it can't
     * see (attribute changes are seen already).
     */
    invalidate(): void;
}
/**
 * Define an effect from a function, with no class to write:
 * `definePixelFilter("pixel-invert", (image, element) => image)`.
 * The function receives the ImageData and the effect element (to read
 * its attributes), and returns an ImageData.
 * @param {string} name the tag name
 * @param {(image: ImageData, element: PixelFilter) => ImageData} transform
 * @returns {CustomElementConstructor}
 */
export declare function definePixelFilter(name: string, transform: (image: ImageData, element: PixelFilter) => ImageData): CustomElementConstructor;
/**
 * @param {string} color
 * @returns {[number, number, number, number] | null} null if it isn't a color
 */
export declare function parseColor(color: string): [number, number, number, number] | null;
