// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * @param {ImageData} image
 * @param {number} count how many colors (at most)
 * @returns {number[][]} `[r, g, b]` triples, most common first
 */
export declare function dominantColors(image: ImageData, count: number): number[][];
/**
 * `[r, g, b]` as `#rrggbb`.
 * @param {number[]} rgb
 * @returns {string}
 */
export declare const toHex: ([r, g, b]: number[]) => string;
