// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * The `u_name` uniforms a shader uses beyond the built-in ones, as
 * parameter names (`u_line_width` -> `line-width`).
 * @param {string} source
 * @returns {string[]}
 */
export declare function shaderParams(source: string): string[];
/**
 * Run `image` through the shader `source`, with `params` for its uniforms.
 * Throws if WebGL2 isn't available or the shader doesn't compile.
 * @param {ImageData} image
 * @param {string} source
 * @param {Record<string, string>} [params]
 * @param {{ time?: number, frame?: number }} [clock]
 * @returns {ImageData}
 */
export declare function runShader(image: ImageData, source: string, params?: Record<string, string>, { time, frame }?: {
    time?: number;
    frame?: number;
}): ImageData;
/**
 * Register a shader as an effect: usable as `name(…)` in an `effects`
 * attribute and as a `<pixel-name>` element, with its `u_` uniforms as
 * parameters (in the order given, or the order they appear).
 * @param {string} name
 * @param {string} source GLSL (see the top of shader.mjs for what's provided)
 * @param {{ params?: string[] }} [options]
 */
export declare function definePixelShader(name: string, source: string, { params }?: {
    params?: string[];
}): import("./effects.mjs").Effect;
